/* GENERATED by scripts/gen-plates.mjs — do not hand-edit.
 *
 * Stand-in catalogue imagery: orthographic elevation plates drawn from each
 * piece's real dimensions, with the blur placeholder and the measured anchor box
 * that the dimension overlay draws against. Replaced wholesale by real
 * photography once the merchant's shoot lands.
 */
import type { MediaAnchors } from './types';

export interface GeneratedPlate {
  path: string;
  width: number;
  height: number;
  blurDataUrl: string;
  anchors: MediaAnchors;
}

export const PLATES: Record<string, GeneratedPlate> = {
  "kaputei-three-seat-sofa:wide": {
    "path": "/media/kaputei-three-seat-sofa-wide.webp",
    "width": 1600,
    "height": 1200,
    "blurDataUrl": "data:image/webp;base64,UklGRiQAAABXRUJQVlA4IBgAAAAwAQCdASoMAAkAAsBIJaQAA3AA/vdCAAA=",
    "anchors": {
      "x1": 0.1275,
      "y1": 0.3359,
      "x2": 0.8725,
      "y2": 0.7049
    }
  },
  "kaputei-three-seat-sofa:square": {
    "path": "/media/kaputei-three-seat-sofa-square.webp",
    "width": 1200,
    "height": 1200,
    "blurDataUrl": "data:image/webp;base64,UklGRiQAAABXRUJQVlA4IBgAAAAwAQCdASoMAAwAAsBIJaQAA3AA/vdCAAA=",
    "anchors": {
      "x1": 0.17,
      "y1": 0.3978,
      "x2": 0.83,
      "y2": 0.643
    }
  },
  "kaputei-three-seat-sofa:pano": {
    "path": "/media/kaputei-three-seat-sofa-pano.webp",
    "width": 1600,
    "height": 900,
    "blurDataUrl": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4WAoAAAAQAAAACwAABgAAQUxQSBYAAAABF3Dx/4iIgiAQZH+EDU50hYj+J/KmVlA4IBoAAAAwAQCdASoMAAcAAsBIJaQAA3AA/vdGeBAAAA==",
    "anchors": {
      "x1": 0.0956,
      "y1": 0.2534,
      "x2": 0.9044,
      "y2": 0.7874
    }
  },
  "kaputei-three-seat-sofa:v0:wide": {
    "path": "/media/kaputei-three-seat-sofa-v0-wide.webp",
    "width": 1600,
    "height": 1200,
    "blurDataUrl": "data:image/webp;base64,UklGRi4AAABXRUJQVlA4ICIAAAAwAQCdASoMAAkAAsBIJaQAA3AA/vcsmfSgd5E3rQh4SEAA",
    "anchors": {
      "x1": 0.1275,
      "y1": 0.3359,
      "x2": 0.8725,
      "y2": 0.7049
    }
  },
  "kaputei-three-seat-sofa:v0:square": {
    "path": "/media/kaputei-three-seat-sofa-v0-square.webp",
    "width": 1200,
    "height": 1200,
    "blurDataUrl": "data:image/webp;base64,UklGRiwAAABXRUJQVlA4ICAAAAAwAQCdASoMAAwAAsBIJaQAA3AA/vcsdOvRYalvomoAAA==",
    "anchors": {
      "x1": 0.17,
      "y1": 0.3978,
      "x2": 0.83,
      "y2": 0.643
    }
  },
  "kaputei-three-seat-sofa:v1:wide": {
    "path": "/media/kaputei-three-seat-sofa-v1-wide.webp",
    "width": 1600,
    "height": 1200,
    "blurDataUrl": "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAACQAQCdASoMAAkAAsBIJaQAAudUwMAA/vj671KpSVLCUhxgiuziBQQGpKXwsDUAAAA=",
    "anchors": {
      "x1": 0.1275,
      "y1": 0.3359,
      "x2": 0.8725,
      "y2": 0.7049
    }
  },
  "kaputei-three-seat-sofa:v1:square": {
    "path": "/media/kaputei-three-seat-sofa-v1-square.webp",
    "width": 1200,
    "height": 1200,
    "blurDataUrl": "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAACwAQCdASoMAAwAAsBIJaQAAubLG2VAAP76pwQ/f9OcvxKsFIjSXJ8sZyl12xmIAAA=",
    "anchors": {
      "x1": 0.17,
      "y1": 0.3978,
      "x2": 0.83,
      "y2": 0.643
    }
  },
  "kaputei-three-seat-sofa:v2:wide": {
    "path": "/media/kaputei-three-seat-sofa-v2-wide.webp",
    "width": 1600,
    "height": 1200,
    "blurDataUrl": "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAADQAQCdASoMAAkAAsBIJZQCdAEPC+ZQAAD++Zki4mOT8jmnCxQj44dV3cLDplwWaFXXitPgAAA=",
    "anchors": {
      "x1": 0.1275,
      "y1": 0.3359,
      "x2": 0.8725,
      "y2": 0.7049
    }
  },
  "kaputei-three-seat-sofa:v2:square": {
    "path": "/media/kaputei-three-seat-sofa-v2-square.webp",
    "width": 1200,
    "height": 1200,
    "blurDataUrl": "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAACwAQCdASoMAAwAAsBIJZQCw7EOhygAAP76pwi5ipvLQbG4u1IBZr35k5h4p2kgAAA=",
    "anchors": {
      "x1": 0.17,
      "y1": 0.3978,
      "x2": 0.83,
      "y2": 0.643
    }
  },
  "kaputei-two-seat-sofa:wide": {
    "path": "/media/kaputei-two-seat-sofa-wide.webp",
    "width": 1600,
    "height": 1200,
    "blurDataUrl": "data:image/webp;base64,UklGRiQAAABXRUJQVlA4IBgAAAAwAQCdASoMAAkAAsBIJaQAA3AA/vdCAAA=",
    "anchors": {
      "x1": 0.1275,
      "y1": 0.2721,
      "x2": 0.8725,
      "y2": 0.7687
    }
  },
  "kaputei-two-seat-sofa:square": {
    "path": "/media/kaputei-two-seat-sofa-square.webp",
    "width": 1200,
    "height": 1200,
    "blurDataUrl": "data:image/webp;base64,UklGRiQAAABXRUJQVlA4IBgAAAAwAQCdASoMAAwAAsBIJaQAA3AA/vdCAAA=",
    "anchors": {
      "x1": 0.17,
      "y1": 0.3554,
      "x2": 0.83,
      "y2": 0.6854
    }
  },
  "kaputei-two-seat-sofa:pano": {
    "path": "/media/kaputei-two-seat-sofa-pano.webp",
    "width": 1600,
    "height": 900,
    "blurDataUrl": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4WAoAAAAQAAAACwAABgAAQUxQSBYAAAABF3Dx/4iIgiAQZH+EDU50hYj+J/KmVlA4IBoAAAAwAQCdASoMAAcAAsBIJaQAA3AA/vdGeBAAAA==",
    "anchors": {
      "x1": 0.1288,
      "y1": 0.1904,
      "x2": 0.8713,
      "y2": 0.8504
    }
  },
  "kaputei-two-seat-sofa:v0:wide": {
    "path": "/media/kaputei-two-seat-sofa-v0-wide.webp",
    "width": 1600,
    "height": 1200,
    "blurDataUrl": "data:image/webp;base64,UklGRjAAAABXRUJQVlA4ICQAAACwAQCdASoMAAkAAsBIJZwAAu18Zx6AAP76IPtYbtQ2DHCAAAA=",
    "anchors": {
      "x1": 0.1275,
      "y1": 0.2721,
      "x2": 0.8725,
      "y2": 0.7687
    }
  },
  "kaputei-two-seat-sofa:v0:square": {
    "path": "/media/kaputei-two-seat-sofa-v0-square.webp",
    "width": 1200,
    "height": 1200,
    "blurDataUrl": "data:image/webp;base64,UklGRjAAAABXRUJQVlA4ICQAAAAwAQCdASoMAAwAAsBIJZwAA3AA/vcF9F8yER68zdxuxCAgAAA=",
    "anchors": {
      "x1": 0.17,
      "y1": 0.3554,
      "x2": 0.83,
      "y2": 0.6854
    }
  },
  "kaputei-two-seat-sofa:v1:wide": {
    "path": "/media/kaputei-two-seat-sofa-v1-wide.webp",
    "width": 1600,
    "height": 1200,
    "blurDataUrl": "data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAACQAQCdASoMAAkAAsBIJaQAAuQcBPAA/vdfbuEfIdabVy9VY83VHYPu8B3Qjh4FoAAAAA==",
    "anchors": {
      "x1": 0.1275,
      "y1": 0.2721,
      "x2": 0.8725,
      "y2": 0.7687
    }
  },
  "kaputei-two-seat-sofa:v1:square": {
    "path": "/media/kaputei-two-seat-sofa-v1-square.webp",
    "width": 1200,
    "height": 1200,
    "blurDataUrl": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAADQAQCdASoMAAwAAsBIJaQAAucSixisAAD++qbvLqyL2PreRMpl823vjAkOOAAA",
    "anchors": {
      "x1": 0.17,
      "y1": 0.3554,
      "x2": 0.83,
      "y2": 0.6854
    }
  },
  "loita-armchair:wide": {
    "path": "/media/loita-armchair-wide.webp",
    "width": 1600,
    "height": 1200,
    "blurDataUrl": "data:image/webp;base64,UklGRiQAAABXRUJQVlA4IBgAAAAwAQCdASoMAAkAAsBIJaQAA3AA/vdCAAA=",
    "anchors": {
      "x1": 0.2592,
      "y1": 0.1904,
      "x2": 0.7408,
      "y2": 0.8504
    }
  },
  "loita-armchair:square": {
    "path": "/media/loita-armchair-square.webp",
    "width": 1200,
    "height": 1200,
    "blurDataUrl": "data:image/webp;base64,UklGRiQAAABXRUJQVlA4IBgAAAAwAQCdASoMAAwAAsBIJaQAA3AA/vdCAAA=",
    "anchors": {
      "x1": 0.1789,
      "y1": 0.1904,
      "x2": 0.8211,
      "y2": 0.8504
    }
  },
  "loita-armchair:pano": {
    "path": "/media/loita-armchair-pano.webp",
    "width": 1600,
    "height": 900,
    "blurDataUrl": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4WAoAAAAQAAAACwAABgAAQUxQSBUAAAABF3Dx/4iIgiDbZv4mr+gVIvqf6A0AVlA4IBoAAABQAQCdASoMAAcAAsBIJaQABAAAAP73ZwAAAA==",
    "anchors": {
      "x1": 0.3194,
      "y1": 0.1904,
      "x2": 0.6806,
      "y2": 0.8504
    }
  },
  "loita-armchair:v0:wide": {
    "path": "/media/loita-armchair-v0-wide.webp",
    "width": 1600,
    "height": 1200,
    "blurDataUrl": "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAADwAQCdASoMAAkAAsBIJYwCw7EUWffm34AA/vo4mJZIAvqPXrybEaw/dVq96JY/kN88AAAA",
    "anchors": {
      "x1": 0.2592,
      "y1": 0.1904,
      "x2": 0.7408,
      "y2": 0.8504
    }
  },
  "loita-armchair:v0:square": {
    "path": "/media/loita-armchair-v0-square.webp",
    "width": 1200,
    "height": 1200,
    "blurDataUrl": "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAADQAQCdASoMAAwAAsBIJQBOgCHfvkgCAAD++ZYTVsSRQiosOxO+sq32KorKDjPkxEwctl5AAAA=",
    "anchors": {
      "x1": 0.1789,
      "y1": 0.1904,
      "x2": 0.8211,
      "y2": 0.8504
    }
  },
  "loita-armchair:v1:wide": {
    "path": "/media/loita-armchair-v1-wide.webp",
    "width": 1600,
    "height": 1200,
    "blurDataUrl": "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAADwAQCdASoMAAkAAsBIJZwC7AEQUGseMAAA/vm1yc+SOL1p1ZtKkIQGpJ0H6sBE95ifkgePBy3eAAAA",
    "anchors": {
      "x1": 0.2592,
      "y1": 0.1904,
      "x2": 0.7408,
      "y2": 0.8504
    }
  },
  "loita-armchair:v1:square": {
    "path": "/media/loita-armchair-v1-square.webp",
    "width": 1200,
    "height": 1200,
    "blurDataUrl": "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAAAQAgCdASoMAAwAAsBIJZQCdAEQUGmIkqgAAP74QF2KtXeGAXt8EbJPFm2wA0OfTjI6p3KAGYnuVBbE4AA=",
    "anchors": {
      "x1": 0.1789,
      "y1": 0.1904,
      "x2": 0.8211,
      "y2": 0.8504
    }
  },
  "nyeri-lounge-chair:wide": {
    "path": "/media/nyeri-lounge-chair-wide.webp",
    "width": 1600,
    "height": 1200,
    "blurDataUrl": "data:image/webp;base64,UklGRiQAAABXRUJQVlA4IBgAAAAwAQCdASoMAAkAAsBIJaQAA3AA/vdnAAA=",
    "anchors": {
      "x1": 0.2242,
      "y1": 0.1904,
      "x2": 0.7758,
      "y2": 0.8504
    }
  },
  "nyeri-lounge-chair:square": {
    "path": "/media/nyeri-lounge-chair-square.webp",
    "width": 1200,
    "height": 1200,
    "blurDataUrl": "data:image/webp;base64,UklGRiQAAABXRUJQVlA4IBgAAAAwAQCdASoMAAwAAsBIJaQAA3AA/vdCAAA=",
    "anchors": {
      "x1": 0.17,
      "y1": 0.2242,
      "x2": 0.83,
      "y2": 0.8166
    }
  },
  "nyeri-lounge-chair:pano": {
    "path": "/media/nyeri-lounge-chair-pano.webp",
    "width": 1600,
    "height": 900,
    "blurDataUrl": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4WAoAAAAQAAAACwAABgAAQUxQSBYAAAABF3Dx/4iIgiAQZH+EDU50hYj+J/KmVlA4IBoAAAAwAQCdASoMAAcAAsBIJaQAA3AA/vdGeBAAAA==",
    "anchors": {
      "x1": 0.2932,
      "y1": 0.1904,
      "x2": 0.7068,
      "y2": 0.8504
    }
  },
  "nyeri-lounge-chair:v0:wide": {
    "path": "/media/nyeri-lounge-chair-v0-wide.webp",
    "width": 1600,
    "height": 1200,
    "blurDataUrl": "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAAAQAgCdASoMAAkAAsBIJZQCw7ERHsbLp3AAAP75A2vRhssTdjk2tmOZYK2U3GdjL7e7HmIAAAA=",
    "anchors": {
      "x1": 0.2242,
      "y1": 0.1904,
      "x2": 0.7758,
      "y2": 0.8504
    }
  },
  "nyeri-lounge-chair:v0:square": {
    "path": "/media/nyeri-lounge-chair-v0-square.webp",
    "width": 1200,
    "height": 1200,
    "blurDataUrl": "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAADQAQCdASoMAAwAAsBIJZQCw7EO+MmgAAD++PrpEgZqB3dJXwEUDMObZMOR7PHviufYfa4AAAA=",
    "anchors": {
      "x1": 0.17,
      "y1": 0.2242,
      "x2": 0.83,
      "y2": 0.8166
    }
  },
  "nyeri-lounge-chair:v1:wide": {
    "path": "/media/nyeri-lounge-chair-v1-wide.webp",
    "width": 1600,
    "height": 1200,
    "blurDataUrl": "data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAAAQAgCdASoMAAkAAsBIJZQCw7ERHzSqgIgAAP75A2vRhy0HuggyrFMLRodPoDBcG78uExMXqAAAAA==",
    "anchors": {
      "x1": 0.2242,
      "y1": 0.1904,
      "x2": 0.7758,
      "y2": 0.8504
    }
  },
  "nyeri-lounge-chair:v1:square": {
    "path": "/media/nyeri-lounge-chair-v1-square.webp",
    "width": 1200,
    "height": 1200,
    "blurDataUrl": "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAADwAQCdASoMAAwAAsBIJYwCw7EUr+GufeAA/vj66RIGanLyA8s3Bz630rRd9pTBjdcqqR4weLeQJpwjPUAAAA==",
    "anchors": {
      "x1": 0.17,
      "y1": 0.2242,
      "x2": 0.83,
      "y2": 0.8166
    }
  },
  "voi-dining-chair:wide": {
    "path": "/media/voi-dining-chair-wide.webp",
    "width": 1600,
    "height": 1200,
    "blurDataUrl": "data:image/webp;base64,UklGRiQAAABXRUJQVlA4IBgAAAAwAQCdASoMAAkAAsBIJaQAA3AA/vdCAAA=",
    "anchors": {
      "x1": 0.3645,
      "y1": 0.1904,
      "x2": 0.6355,
      "y2": 0.8504
    }
  },
  "voi-dining-chair:square": {
    "path": "/media/voi-dining-chair-square.webp",
    "width": 1200,
    "height": 1200,
    "blurDataUrl": "data:image/webp;base64,UklGRiQAAABXRUJQVlA4IBgAAAAwAQCdASoMAAwAAsBIJaQAA3AA/vdCAAA=",
    "anchors": {
      "x1": 0.3193,
      "y1": 0.1904,
      "x2": 0.6807,
      "y2": 0.8504
    }
  },
  "voi-dining-chair:pano": {
    "path": "/media/voi-dining-chair-pano.webp",
    "width": 1600,
    "height": 900,
    "blurDataUrl": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4WAoAAAAQAAAACwAABgAAQUxQSBUAAAABF3Dx/4iIgiDbZv4mr+gVIvqf6A0AVlA4IBoAAABQAQCdASoMAAcAAsBIJaQABAAAAP73ZwAAAA==",
    "anchors": {
      "x1": 0.3983,
      "y1": 0.1904,
      "x2": 0.6017,
      "y2": 0.8504
    }
  },
  "voi-dining-chair:v0:wide": {
    "path": "/media/voi-dining-chair-v0-wide.webp",
    "width": 1600,
    "height": 1200,
    "blurDataUrl": "data:image/webp;base64,UklGRjYAAABXRUJQVlA4ICoAAADQAQCdASoMAAkAAsBIJZQC7ADdIWUWgAD++q33u9olf1rSlOjOhr8AAAA=",
    "anchors": {
      "x1": 0.3645,
      "y1": 0.1904,
      "x2": 0.6355,
      "y2": 0.8504
    }
  },
  "voi-dining-chair:v0:square": {
    "path": "/media/voi-dining-chair-v0-square.webp",
    "width": 1200,
    "height": 1200,
    "blurDataUrl": "data:image/webp;base64,UklGRjYAAABXRUJQVlA4ICoAAADwAQCdASoMAAwAAsBIJZQCw7EUVBKIWgAA/vqtR2gt26M5Ef9QkdxkAAA=",
    "anchors": {
      "x1": 0.3193,
      "y1": 0.1904,
      "x2": 0.6807,
      "y2": 0.8504
    }
  },
  "voi-dining-chair:v1:wide": {
    "path": "/media/voi-dining-chair-v1-wide.webp",
    "width": 1600,
    "height": 1200,
    "blurDataUrl": "data:image/webp;base64,UklGRjIAAABXRUJQVlA4ICYAAADwAQCdASoMAAkAAsBIJZwC7AEPAYDRowAA/vqtsPLYqmUIX+AAAA==",
    "anchors": {
      "x1": 0.3645,
      "y1": 0.1904,
      "x2": 0.6355,
      "y2": 0.8504
    }
  },
  "voi-dining-chair:v1:square": {
    "path": "/media/voi-dining-chair-v1-square.webp",
    "width": 1200,
    "height": 1200,
    "blurDataUrl": "data:image/webp;base64,UklGRjQAAABXRUJQVlA4ICgAAACwAQCdASoMAAwAAsBIJZQCw7DdF1LAAP76rfuTcfPHDS5xNJpwgAAA",
    "anchors": {
      "x1": 0.3193,
      "y1": 0.1904,
      "x2": 0.6807,
      "y2": 0.8504
    }
  },
  "naro-bench:wide": {
    "path": "/media/naro-bench-wide.webp",
    "width": 1600,
    "height": 1200,
    "blurDataUrl": "data:image/webp;base64,UklGRiQAAABXRUJQVlA4IBgAAAAwAQCdASoMAAkAAsBIJaQAA3AA/vdnAAA=",
    "anchors": {
      "x1": 0.1275,
      "y1": 0.3714,
      "x2": 0.8725,
      "y2": 0.6694
    }
  },
  "naro-bench:square": {
    "path": "/media/naro-bench-square.webp",
    "width": 1200,
    "height": 1200,
    "blurDataUrl": "data:image/webp;base64,UklGRiQAAABXRUJQVlA4IBgAAAAwAQCdASoMAAwAAsBIJaQAA3AA/vdCAAA=",
    "anchors": {
      "x1": 0.17,
      "y1": 0.4214,
      "x2": 0.83,
      "y2": 0.6194
    }
  },
  "naro-bench:pano": {
    "path": "/media/naro-bench-pano.webp",
    "width": 1600,
    "height": 900,
    "blurDataUrl": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4WAoAAAAQAAAACwAABgAAQUxQSBYAAAABF3Dx/4iIgiAQZH+EDU50hYj+J/KmVlA4IBoAAAAwAQCdASoMAAcAAsBIJaQAA3AA/vdGeBAAAA==",
    "anchors": {
      "x1": 0.0956,
      "y1": 0.3047,
      "x2": 0.9044,
      "y2": 0.7361
    }
  },
  "naro-bench:v0:wide": {
    "path": "/media/naro-bench-v0-wide.webp",
    "width": 1600,
    "height": 1200,
    "blurDataUrl": "data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAADQAQCdASoMAAkAAsBIJZQCw7EO/JmqAAD++iWMFtUb6UeJX9NzQkeG1k0KHox/1hgAAA==",
    "anchors": {
      "x1": 0.1275,
      "y1": 0.3714,
      "x2": 0.8725,
      "y2": 0.6694
    }
  },
  "naro-bench:v0:square": {
    "path": "/media/naro-bench-v0-square.webp",
    "width": 1200,
    "height": 1200,
    "blurDataUrl": "data:image/webp;base64,UklGRjgAAABXRUJQVlA4ICwAAADQAQCdASoMAAwAAsBIJZQCw7EO/8E90AD++qbfEYH2UsIkB3JhfaSkugAAAA==",
    "anchors": {
      "x1": 0.17,
      "y1": 0.4214,
      "x2": 0.83,
      "y2": 0.6194
    }
  },
  "athi-dining-table:wide": {
    "path": "/media/athi-dining-table-wide.webp",
    "width": 1600,
    "height": 1200,
    "blurDataUrl": "data:image/webp;base64,UklGRiQAAABXRUJQVlA4IBgAAAAwAQCdASoMAAkAAsBIJaQAA3AA/vdCAAA=",
    "anchors": {
      "x1": 0.1275,
      "y1": 0.3135,
      "x2": 0.8725,
      "y2": 0.7273
    }
  },
  "athi-dining-table:square": {
    "path": "/media/athi-dining-table-square.webp",
    "width": 1200,
    "height": 1200,
    "blurDataUrl": "data:image/webp;base64,UklGRiQAAABXRUJQVlA4IBgAAAAwAQCdASoMAAwAAsBIJaQAA3AA/vdCAAA=",
    "anchors": {
      "x1": 0.17,
      "y1": 0.3829,
      "x2": 0.83,
      "y2": 0.6579
    }
  },
  "athi-dining-table:pano": {
    "path": "/media/athi-dining-table-pano.webp",
    "width": 1600,
    "height": 900,
    "blurDataUrl": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4WAoAAAAQAAAACwAABgAAQUxQSBYAAAABF3Dx/4iIgiAQZH+EDU50hYj+J/KmVlA4IBoAAAAwAQCdASoMAAcAAsBIJaQAA3AA/vdGeBAAAA==",
    "anchors": {
      "x1": 0.0956,
      "y1": 0.2209,
      "x2": 0.9044,
      "y2": 0.8199
    }
  },
  "athi-dining-table:v0:wide": {
    "path": "/media/athi-dining-table-v0-wide.webp",
    "width": 1600,
    "height": 1200,
    "blurDataUrl": "data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAADQAQCdASoMAAkAAsBIJZQCdAEO/JmqAAD++ZkUa/F/i4GcojiuZVTz2YbOrrxWnwAAAA==",
    "anchors": {
      "x1": 0.1275,
      "y1": 0.3135,
      "x2": 0.8725,
      "y2": 0.7273
    }
  },
  "athi-dining-table:v0:square": {
    "path": "/media/athi-dining-table-v0-square.webp",
    "width": 1200,
    "height": 1200,
    "blurDataUrl": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAADwAQCdASoMAAwAAsBIJZQCw7EO4/mh9BAA/vqnCZTxjcmNru3x9bj368aCAAAA",
    "anchors": {
      "x1": 0.17,
      "y1": 0.3829,
      "x2": 0.83,
      "y2": 0.6579
    }
  },
  "athi-dining-table:v1:wide": {
    "path": "/media/athi-dining-table-v1-wide.webp",
    "width": 1600,
    "height": 1200,
    "blurDataUrl": "data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAACwAQCdASoMAAkAAsBIJZwCw7ENPxiAAP74+u9eCA2FiI46F1jvNO92Wv42c6kLM9uAAA==",
    "anchors": {
      "x1": 0.1275,
      "y1": 0.3135,
      "x2": 0.8725,
      "y2": 0.7273
    }
  },
  "athi-dining-table:v1:square": {
    "path": "/media/athi-dining-table-v1-square.webp",
    "width": 1200,
    "height": 1200,
    "blurDataUrl": "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAADQAQCdASoMAAwAAsBIJZwC7AEOy58N2AD++qb+M+JG3dQGqt2kEC6M+pPeoRQQAAA=",
    "anchors": {
      "x1": 0.17,
      "y1": 0.3829,
      "x2": 0.83,
      "y2": 0.6579
    }
  },
  "athi-dining-table-240:wide": {
    "path": "/media/athi-dining-table-240-wide.webp",
    "width": 1600,
    "height": 1200,
    "blurDataUrl": "data:image/webp;base64,UklGRiQAAABXRUJQVlA4IBgAAAAwAQCdASoMAAkAAsBIJaQAA3AA/vdnAAA=",
    "anchors": {
      "x1": 0.1275,
      "y1": 0.3652,
      "x2": 0.8725,
      "y2": 0.6756
    }
  },
  "athi-dining-table-240:square": {
    "path": "/media/athi-dining-table-240-square.webp",
    "width": 1200,
    "height": 1200,
    "blurDataUrl": "data:image/webp;base64,UklGRiQAAABXRUJQVlA4IBgAAAAwAQCdASoMAAwAAsBIJaQAA3AA/vdCAAA=",
    "anchors": {
      "x1": 0.17,
      "y1": 0.4173,
      "x2": 0.83,
      "y2": 0.6235
    }
  },
  "athi-dining-table-240:pano": {
    "path": "/media/athi-dining-table-240-pano.webp",
    "width": 1600,
    "height": 900,
    "blurDataUrl": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4WAoAAAAQAAAACwAABgAAQUxQSBYAAAABF3Dx/4iIgiAQZH+EDU50hYj+J/KmVlA4IBoAAAAwAQCdASoMAAcAAsBIJaQAA3AA/vdGeBAAAA==",
    "anchors": {
      "x1": 0.0956,
      "y1": 0.2957,
      "x2": 0.9044,
      "y2": 0.7451
    }
  },
  "athi-dining-table-240:v0:wide": {
    "path": "/media/athi-dining-table-240-v0-wide.webp",
    "width": 1600,
    "height": 1200,
    "blurDataUrl": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAACwAQCdASoMAAkAAsBIJZQCw7EO/EhAAP76JYvoJL0s4W/E2XJQ7C3oi5XlqAAA",
    "anchors": {
      "x1": 0.1275,
      "y1": 0.3652,
      "x2": 0.8725,
      "y2": 0.6756
    }
  },
  "athi-dining-table-240:v0:square": {
    "path": "/media/athi-dining-table-240-v0-square.webp",
    "width": 1200,
    "height": 1200,
    "blurDataUrl": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAACwAQCdASoMAAwAAsBIJZQCw7EO0x6AAP76pwo0RCx5RfvFs5Tv0/p9Lh1wAAAA",
    "anchors": {
      "x1": 0.17,
      "y1": 0.4173,
      "x2": 0.83,
      "y2": 0.6235
    }
  },
  "athi-dining-table-240:v1:wide": {
    "path": "/media/athi-dining-table-240-v1-wide.webp",
    "width": 1600,
    "height": 1200,
    "blurDataUrl": "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAACwAQCdASoMAAkAAsBIJZwAAudV7NBYAP75mSLiY4BxfO4CFVHe4DTmTxhToMZ2xD/gPAAA",
    "anchors": {
      "x1": 0.1275,
      "y1": 0.3652,
      "x2": 0.8725,
      "y2": 0.6756
    }
  },
  "athi-dining-table-240:v1:square": {
    "path": "/media/athi-dining-table-240-v1-square.webp",
    "width": 1200,
    "height": 1200,
    "blurDataUrl": "data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAADQAQCdASoMAAwAAsBIJZwAAudrg4az3AD++qcCc+6uK04bRgdZanxdR9Gp/h1moHAAAA==",
    "anchors": {
      "x1": 0.17,
      "y1": 0.4173,
      "x2": 0.83,
      "y2": 0.6235
    }
  },
  "ruiru-coffee-table:wide": {
    "path": "/media/ruiru-coffee-table-wide.webp",
    "width": 1600,
    "height": 1200,
    "blurDataUrl": "data:image/webp;base64,UklGRiQAAABXRUJQVlA4IBgAAAAwAQCdASoMAAkAAsBIJaQAA3AA/vdnAAA=",
    "anchors": {
      "x1": 0.1275,
      "y1": 0.3548,
      "x2": 0.8725,
      "y2": 0.686
    }
  },
  "ruiru-coffee-table:square": {
    "path": "/media/ruiru-coffee-table-square.webp",
    "width": 1200,
    "height": 1200,
    "blurDataUrl": "data:image/webp;base64,UklGRiQAAABXRUJQVlA4IBgAAAAwAQCdASoMAAwAAsBIJaQAA3AA/vdCAAA=",
    "anchors": {
      "x1": 0.17,
      "y1": 0.4104,
      "x2": 0.83,
      "y2": 0.6304
    }
  },
  "ruiru-coffee-table:pano": {
    "path": "/media/ruiru-coffee-table-pano.webp",
    "width": 1600,
    "height": 900,
    "blurDataUrl": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4WAoAAAAQAAAACwAABgAAQUxQSBYAAAABF3Dx/4iIgiAQZH+EDU50hYj+J/KmVlA4IBoAAAAwAQCdASoMAAcAAsBIJaQAA3AA/vdGeBAAAA==",
    "anchors": {
      "x1": 0.0956,
      "y1": 0.2808,
      "x2": 0.9044,
      "y2": 0.76
    }
  },
  "ruiru-coffee-table:v0:wide": {
    "path": "/media/ruiru-coffee-table-v0-wide.webp",
    "width": 1600,
    "height": 1200,
    "blurDataUrl": "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAADQAQCdASoMAAkAAsBIJZQCw7EPhr3MAAD++jjl4HjqrtNPdZe+GbIZriIwUqcAAAA=",
    "anchors": {
      "x1": 0.1275,
      "y1": 0.3548,
      "x2": 0.8725,
      "y2": 0.686
    }
  },
  "ruiru-coffee-table:v0:square": {
    "path": "/media/ruiru-coffee-table-v0-square.webp",
    "width": 1200,
    "height": 1200,
    "blurDataUrl": "data:image/webp;base64,UklGRjgAAABXRUJQVlA4ICwAAACwAQCdASoMAAwAAsBIJZQCw7EO+ePAAP76pvgI4ldro96tr31vkR4lMl0AAA==",
    "anchors": {
      "x1": 0.17,
      "y1": 0.4104,
      "x2": 0.83,
      "y2": 0.6304
    }
  },
  "ruiru-coffee-table:v1:wide": {
    "path": "/media/ruiru-coffee-table-v1-wide.webp",
    "width": 1600,
    "height": 1200,
    "blurDataUrl": "data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAACQAQCdASoMAAkAAsBIJZwAAudVCYAA/vmZJABS8EBNATHyn4NueYCtVPBqilgkvYAAAA==",
    "anchors": {
      "x1": 0.1275,
      "y1": 0.3548,
      "x2": 0.8725,
      "y2": 0.686
    }
  },
  "ruiru-coffee-table:v1:square": {
    "path": "/media/ruiru-coffee-table-v1-square.webp",
    "width": 1200,
    "height": 1200,
    "blurDataUrl": "data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAACwAQCdASoMAAwAAsBIJZwAAubLG2boAP76pwci3FwvswxegdZbAKdsNi9O8z8RxQAAAA==",
    "anchors": {
      "x1": 0.17,
      "y1": 0.4104,
      "x2": 0.83,
      "y2": 0.6304
    }
  },
  "tana-side-table:wide": {
    "path": "/media/tana-side-table-wide.webp",
    "width": 1600,
    "height": 1200,
    "blurDataUrl": "data:image/webp;base64,UklGRiQAAABXRUJQVlA4IBgAAAAwAQCdASoMAAkAAsBIJaQAA3AA/vdnAAA=",
    "anchors": {
      "x1": 0.2975,
      "y1": 0.1904,
      "x2": 0.7025,
      "y2": 0.8504
    }
  },
  "tana-side-table:square": {
    "path": "/media/tana-side-table-square.webp",
    "width": 1200,
    "height": 1200,
    "blurDataUrl": "data:image/webp;base64,UklGRiQAAABXRUJQVlA4IBgAAAAwAQCdASoMAAwAAsBIJaQAA3AA/vdCAAA=",
    "anchors": {
      "x1": 0.23,
      "y1": 0.1904,
      "x2": 0.77,
      "y2": 0.8504
    }
  },
  "tana-side-table:pano": {
    "path": "/media/tana-side-table-pano.webp",
    "width": 1600,
    "height": 900,
    "blurDataUrl": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4WAoAAAAQAAAACwAABgAAQUxQSBUAAAABF3Dx/4iIgiDbZv4mr+gVIvqf6A0AVlA4IBoAAABQAQCdASoMAAcAAsBIJaQABAAAAP73ZwAAAA==",
    "anchors": {
      "x1": 0.3481,
      "y1": 0.1904,
      "x2": 0.6519,
      "y2": 0.8504
    }
  },
  "tana-side-table:v0:wide": {
    "path": "/media/tana-side-table-v0-wide.webp",
    "width": 1600,
    "height": 1200,
    "blurDataUrl": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAADwAQCdASoMAAkAAsBIJYwC7AEUU/2BTwAA/vrEkPHrfbQ3gw/NAI+M7nFoAAAA",
    "anchors": {
      "x1": 0.2975,
      "y1": 0.1904,
      "x2": 0.7025,
      "y2": 0.8504
    }
  },
  "tana-side-table:v0:square": {
    "path": "/media/tana-side-table-v0-square.webp",
    "width": 1200,
    "height": 1200,
    "blurDataUrl": "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAADwAQCdASoMAAwAAsBIJYwCw7EUiHyyN8AA/vo4mKD8sRWWFOelk2s3q+4wqwYkwVRQIAAA",
    "anchors": {
      "x1": 0.23,
      "y1": 0.1904,
      "x2": 0.77,
      "y2": 0.8504
    }
  },
  "tana-side-table:v1:wide": {
    "path": "/media/tana-side-table-v1-wide.webp",
    "width": 1600,
    "height": 1200,
    "blurDataUrl": "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAAAQAgCdASoMAAkAAsBIJZwC7ADp8+42XYAAAP76OJii6vsWhZ6rR8WwgFxm4/4/lEVjlPgA",
    "anchors": {
      "x1": 0.2975,
      "y1": 0.1904,
      "x2": 0.7025,
      "y2": 0.8504
    }
  },
  "tana-side-table:v1:square": {
    "path": "/media/tana-side-table-v1-square.webp",
    "width": 1200,
    "height": 1200,
    "blurDataUrl": "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAADwAQCdASoMAAwAAsBIJZQCw7ERHsO9pQAA/vmtwHPXzR/giPc7XET7hhRhKYndb8IWAqlGYe5NwAAA",
    "anchors": {
      "x1": 0.23,
      "y1": 0.1904,
      "x2": 0.77,
      "y2": 0.8504
    }
  },
  "chania-writing-desk:wide": {
    "path": "/media/chania-writing-desk-wide.webp",
    "width": 1600,
    "height": 1200,
    "blurDataUrl": "data:image/webp;base64,UklGRiQAAABXRUJQVlA4IBgAAAAwAQCdASoMAAkAAsBIJaQAA3AA/vdnAAA=",
    "anchors": {
      "x1": 0.1275,
      "y1": 0.2543,
      "x2": 0.8725,
      "y2": 0.7865
    }
  },
  "chania-writing-desk:square": {
    "path": "/media/chania-writing-desk-square.webp",
    "width": 1200,
    "height": 1200,
    "blurDataUrl": "data:image/webp;base64,UklGRiQAAABXRUJQVlA4IBgAAAAwAQCdASoMAAwAAsBIJaQAA3AA/vdCAAA=",
    "anchors": {
      "x1": 0.17,
      "y1": 0.3436,
      "x2": 0.83,
      "y2": 0.6972
    }
  },
  "chania-writing-desk:pano": {
    "path": "/media/chania-writing-desk-pano.webp",
    "width": 1600,
    "height": 900,
    "blurDataUrl": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4WAoAAAAQAAAACwAABgAAQUxQSBYAAAABF3Dx/4iIgiAQZH+EDU50hYj+J/KmVlA4IBoAAAAwAQCdASoMAAcAAsBIJaQAA3AA/vdGeBAAAA==",
    "anchors": {
      "x1": 0.1535,
      "y1": 0.1904,
      "x2": 0.8465,
      "y2": 0.8504
    }
  },
  "chania-writing-desk:v0:wide": {
    "path": "/media/chania-writing-desk-v0-wide.webp",
    "width": 1600,
    "height": 1200,
    "blurDataUrl": "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAADwAQCdASoMAAkAAsBIJYwCdAEUr+HKdIAA/vmY4v4lKWRL/xb+o1Md6td2qNtMgAA=",
    "anchors": {
      "x1": 0.1275,
      "y1": 0.2543,
      "x2": 0.8725,
      "y2": 0.7865
    }
  },
  "chania-writing-desk:v0:square": {
    "path": "/media/chania-writing-desk-v0-square.webp",
    "width": 1200,
    "height": 1200,
    "blurDataUrl": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAADQAQCdASoMAAwAAsBIJZQCw7EOiKykwAD++qcJlCJidb1l9nI7P+0PdgwkAAAA",
    "anchors": {
      "x1": 0.17,
      "y1": 0.3436,
      "x2": 0.83,
      "y2": 0.6972
    }
  },
  "chania-writing-desk:v1:wide": {
    "path": "/media/chania-writing-desk-v1-wide.webp",
    "width": 1600,
    "height": 1200,
    "blurDataUrl": "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAADQAQCdASoMAAkAAsBIJZQCdAEQUHw7QAD+92nC5VF1JBP0er7bgSXdUcqkxetYP+8gu34QAAA=",
    "anchors": {
      "x1": 0.1275,
      "y1": 0.2543,
      "x2": 0.8725,
      "y2": 0.7865
    }
  },
  "chania-writing-desk:v1:square": {
    "path": "/media/chania-writing-desk-v1-square.webp",
    "width": 1200,
    "height": 1200,
    "blurDataUrl": "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAADQAQCdASoMAAwAAsBIJZwC7AEOjEztAAD++qbvLZx90TL/BV/EB6Xjzt2jotFdQrMaAAAA",
    "anchors": {
      "x1": 0.17,
      "y1": 0.3436,
      "x2": 0.83,
      "y2": 0.6972
    }
  },
  "meru-sideboard:wide": {
    "path": "/media/meru-sideboard-wide.webp",
    "width": 1600,
    "height": 1200,
    "blurDataUrl": "data:image/webp;base64,UklGRiQAAABXRUJQVlA4IBgAAAAwAQCdASoMAAkAAsBIJaQAA3AA/vdnAAA=",
    "anchors": {
      "x1": 0.1275,
      "y1": 0.2721,
      "x2": 0.8725,
      "y2": 0.7687
    }
  },
  "meru-sideboard:square": {
    "path": "/media/meru-sideboard-square.webp",
    "width": 1200,
    "height": 1200,
    "blurDataUrl": "data:image/webp;base64,UklGRiQAAABXRUJQVlA4IBgAAAAwAQCdASoMAAwAAsBIJaQAA3AA/vdCAAA=",
    "anchors": {
      "x1": 0.17,
      "y1": 0.3554,
      "x2": 0.83,
      "y2": 0.6854
    }
  },
  "meru-sideboard:pano": {
    "path": "/media/meru-sideboard-pano.webp",
    "width": 1600,
    "height": 900,
    "blurDataUrl": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4WAoAAAAQAAAACwAABgAAQUxQSBYAAAABF3Dx/4iIgiAQZH+EDU50hYj+J/KmVlA4IBoAAAAwAQCdASoMAAcAAsBIJaQAA3AA/vdGeBAAAA==",
    "anchors": {
      "x1": 0.1288,
      "y1": 0.1904,
      "x2": 0.8713,
      "y2": 0.8504
    }
  },
  "meru-sideboard:v0:wide": {
    "path": "/media/meru-sideboard-v0-wide.webp",
    "width": 1600,
    "height": 1200,
    "blurDataUrl": "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAADQAQCdASoMAAkAAsBIJYwCdAEO/JmqAAD++Zjh+DbkB10rPrpC3oyorN92qNtMgAA=",
    "anchors": {
      "x1": 0.1275,
      "y1": 0.2721,
      "x2": 0.8725,
      "y2": 0.7687
    }
  },
  "meru-sideboard:v0:square": {
    "path": "/media/meru-sideboard-v0-square.webp",
    "width": 1200,
    "height": 1200,
    "blurDataUrl": "data:image/webp;base64,UklGRjgAAABXRUJQVlA4ICwAAADwAQCdASoMAAwAAsBIJZQC7AEO4NDWnAAA/vqnCZQiYnW9ZffYjxjFBAAAAA==",
    "anchors": {
      "x1": 0.17,
      "y1": 0.3554,
      "x2": 0.83,
      "y2": 0.6854
    }
  },
  "meru-sideboard:v1:wide": {
    "path": "/media/meru-sideboard-v1-wide.webp",
    "width": 1600,
    "height": 1200,
    "blurDataUrl": "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAADwAQCdASoMAAkAAsBIJZQCw7EUr+HKEAAA/vg3OwQAT4kFwWPjEDmEG+n/No/+2EMHWIAA",
    "anchors": {
      "x1": 0.1275,
      "y1": 0.2721,
      "x2": 0.8725,
      "y2": 0.7687
    }
  },
  "meru-sideboard:v1:square": {
    "path": "/media/meru-sideboard-v1-square.webp",
    "width": 1200,
    "height": 1200,
    "blurDataUrl": "data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAADwAQCdASoMAAwAAsBIJZwC7AEO5JaQzAAA/vqm7y6si9d2LNc0U823vlOyQT3rPAAAAA==",
    "anchors": {
      "x1": 0.17,
      "y1": 0.3554,
      "x2": 0.83,
      "y2": 0.6854
    }
  },
  "meru-sideboard:v2:wide": {
    "path": "/media/meru-sideboard-v2-wide.webp",
    "width": 1600,
    "height": 1200,
    "blurDataUrl": "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAADwAQCdASoMAAkAAsBIJZQCdAEUr+HKEAAA/vdfbvg5WVjuae1Upkna1va/eedtYqJO1NWqAAA=",
    "anchors": {
      "x1": 0.1275,
      "y1": 0.2721,
      "x2": 0.8725,
      "y2": 0.7687
    }
  },
  "meru-sideboard:v2:square": {
    "path": "/media/meru-sideboard-v2-square.webp",
    "width": 1200,
    "height": 1200,
    "blurDataUrl": "data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAADwAQCdASoMAAwAAsBIJZQCw7EO5JaQzAAA/vqm7y6si9j63kTKZfNt75TmvkkhAIAAAA==",
    "anchors": {
      "x1": 0.17,
      "y1": 0.3554,
      "x2": 0.83,
      "y2": 0.6854
    }
  },
  "kericho-bookshelf:wide": {
    "path": "/media/kericho-bookshelf-wide.webp",
    "width": 1600,
    "height": 1200,
    "blurDataUrl": "data:image/webp;base64,UklGRiQAAABXRUJQVlA4IBgAAAAwAQCdASoMAAkAAsBIJaQAA3AA/vdCAAA=",
    "anchors": {
      "x1": 0.3828,
      "y1": 0.1904,
      "x2": 0.6172,
      "y2": 0.8504
    }
  },
  "kericho-bookshelf:square": {
    "path": "/media/kericho-bookshelf-square.webp",
    "width": 1200,
    "height": 1200,
    "blurDataUrl": "data:image/webp;base64,UklGRiQAAABXRUJQVlA4IBgAAAAwAQCdASoMAAwAAsBIJaQAA3AA/vdCAAA=",
    "anchors": {
      "x1": 0.3437,
      "y1": 0.1904,
      "x2": 0.6563,
      "y2": 0.8504
    }
  },
  "kericho-bookshelf:pano": {
    "path": "/media/kericho-bookshelf-pano.webp",
    "width": 1600,
    "height": 900,
    "blurDataUrl": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4WAoAAAAQAAAACwAABgAAQUxQSBUAAAABF3Dx/4iIgkAQwl7PdNSFiP4n8qYAVlA4IBoAAAAwAQCdASoMAAcAAsBIJaQAA3AA/vdGeBAAAA==",
    "anchors": {
      "x1": 0.4121,
      "y1": 0.1904,
      "x2": 0.5879,
      "y2": 0.8504
    }
  },
  "kericho-bookshelf:v0:wide": {
    "path": "/media/kericho-bookshelf-v0-wide.webp",
    "width": 1600,
    "height": 1200,
    "blurDataUrl": "data:image/webp;base64,UklGRjQAAABXRUJQVlA4ICgAAADQAQCdASoMAAkAAsBIJZQC7AD0iE1tAAD++q359EAVUPWkUSIQAAAA",
    "anchors": {
      "x1": 0.3828,
      "y1": 0.1904,
      "x2": 0.6172,
      "y2": 0.8504
    }
  },
  "kericho-bookshelf:v0:square": {
    "path": "/media/kericho-bookshelf-v0-square.webp",
    "width": 1200,
    "height": 1200,
    "blurDataUrl": "data:image/webp;base64,UklGRjYAAABXRUJQVlA4ICoAAADwAQCdASoMAAwAAsBIJYwCw7EUVBKIWgAA/vqtR2gt26M5Ef9QfQuQAAA=",
    "anchors": {
      "x1": 0.3437,
      "y1": 0.1904,
      "x2": 0.6563,
      "y2": 0.8504
    }
  },
  "kericho-bookshelf:v1:wide": {
    "path": "/media/kericho-bookshelf-v1-wide.webp",
    "width": 1600,
    "height": 1200,
    "blurDataUrl": "data:image/webp;base64,UklGRjYAAABXRUJQVlA4ICoAAADQAQCdASoMAAkAAsBIJZwC7ADdHvmOcAD++q3kToXGzKJzXoduCdgHgAA=",
    "anchors": {
      "x1": 0.3828,
      "y1": 0.1904,
      "x2": 0.6172,
      "y2": 0.8504
    }
  },
  "kericho-bookshelf:v1:square": {
    "path": "/media/kericho-bookshelf-v1-square.webp",
    "width": 1200,
    "height": 1200,
    "blurDataUrl": "data:image/webp;base64,UklGRjgAAABXRUJQVlA4ICwAAADQAQCdASoMAAwAAsBIJZQCw7DdF78MAAD++q3MHonVXr5qNqcOJJQA0v/0AA==",
    "anchors": {
      "x1": 0.3437,
      "y1": 0.1904,
      "x2": 0.6563,
      "y2": 0.8504
    }
  },
  "sagana-wardrobe:wide": {
    "path": "/media/sagana-wardrobe-wide.webp",
    "width": 1600,
    "height": 1200,
    "blurDataUrl": "data:image/webp;base64,UklGRiQAAABXRUJQVlA4IBgAAAAwAQCdASoMAAkAAsBIJaQAA3AA/vdnAAA=",
    "anchors": {
      "x1": 0.2879,
      "y1": 0.1904,
      "x2": 0.7121,
      "y2": 0.8504
    }
  },
  "sagana-wardrobe:square": {
    "path": "/media/sagana-wardrobe-square.webp",
    "width": 1200,
    "height": 1200,
    "blurDataUrl": "data:image/webp;base64,UklGRiQAAABXRUJQVlA4IBgAAAAwAQCdASoMAAwAAsBIJaQAA3AA/vdCAAA=",
    "anchors": {
      "x1": 0.2171,
      "y1": 0.1904,
      "x2": 0.7829,
      "y2": 0.8504
    }
  },
  "sagana-wardrobe:pano": {
    "path": "/media/sagana-wardrobe-pano.webp",
    "width": 1600,
    "height": 900,
    "blurDataUrl": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4WAoAAAAQAAAACwAABgAAQUxQSBYAAAABF3Dx/4iIgiAQZH+EDU50hYj+J/KmVlA4IBoAAAAwAQCdASoMAAcAAsBIJaQAA3AA/vdGeBAAAA==",
    "anchors": {
      "x1": 0.3409,
      "y1": 0.1904,
      "x2": 0.6591,
      "y2": 0.8504
    }
  },
  "sagana-wardrobe:v0:wide": {
    "path": "/media/sagana-wardrobe-v0-wide.webp",
    "width": 1600,
    "height": 1200,
    "blurDataUrl": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAADwAQCdASoMAAkAAsBIJYwC7AEUVBWiaAAA/vo2WyB6j+ouL3racKaf/ThrMmAA",
    "anchors": {
      "x1": 0.2879,
      "y1": 0.1904,
      "x2": 0.7121,
      "y2": 0.8504
    }
  },
  "sagana-wardrobe:v0:square": {
    "path": "/media/sagana-wardrobe-v0-square.webp",
    "width": 1200,
    "height": 1200,
    "blurDataUrl": "data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAADwAQCdASoMAAwAAsBIJQBYdiKV+5OE+CgA/vo4hbUoJ82NaAfAfZy+Tr0oFDGFlEgAAA==",
    "anchors": {
      "x1": 0.2171,
      "y1": 0.1904,
      "x2": 0.7829,
      "y2": 0.8504
    }
  },
  "sagana-wardrobe:v1:wide": {
    "path": "/media/sagana-wardrobe-v1-wide.webp",
    "width": 1600,
    "height": 1200,
    "blurDataUrl": "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAACwAQCdASoMAAkAAsBIJZQC7ADp7UoAAP76TFkMUEPnUYcX1yh77SbSCxVHGFHXiPZMnB0/gAA=",
    "anchors": {
      "x1": 0.2879,
      "y1": 0.1904,
      "x2": 0.7121,
      "y2": 0.8504
    }
  },
  "sagana-wardrobe:v1:square": {
    "path": "/media/sagana-wardrobe-v1-square.webp",
    "width": 1200,
    "height": 1200,
    "blurDataUrl": "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAADwAQCdASoMAAwAAsBIJYwCw7ERHsPJ5jgA/vkDa/Pal5uknasIWsA+lUkePan68m0+nfF9XOVdqwAA",
    "anchors": {
      "x1": 0.2171,
      "y1": 0.1904,
      "x2": 0.7829,
      "y2": 0.8504
    }
  },
  "mara-bed-frame:wide": {
    "path": "/media/mara-bed-frame-wide.webp",
    "width": 1600,
    "height": 1200,
    "blurDataUrl": "data:image/webp;base64,UklGRiQAAABXRUJQVlA4IBgAAAAwAQCdASoMAAkAAsBIJaQAA3AA/vdCAAA=",
    "anchors": {
      "x1": 0.1275,
      "y1": 0.2495,
      "x2": 0.8725,
      "y2": 0.7913
    }
  },
  "mara-bed-frame:square": {
    "path": "/media/mara-bed-frame-square.webp",
    "width": 1200,
    "height": 1200,
    "blurDataUrl": "data:image/webp;base64,UklGRiQAAABXRUJQVlA4IBgAAAAwAQCdASoMAAwAAsBIJaQAA3AA/vdCAAA=",
    "anchors": {
      "x1": 0.17,
      "y1": 0.3404,
      "x2": 0.83,
      "y2": 0.7004
    }
  },
  "mara-bed-frame:pano": {
    "path": "/media/mara-bed-frame-pano.webp",
    "width": 1600,
    "height": 900,
    "blurDataUrl": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4WAoAAAAQAAAACwAABgAAQUxQSBUAAAABF3Dx/4iIgkAQwl7PdNSFiP4n8qYAVlA4IBoAAAAwAQCdASoMAAcAAsBIJaQAA3AA/vdGeBAAAA==",
    "anchors": {
      "x1": 0.1597,
      "y1": 0.1904,
      "x2": 0.8403,
      "y2": 0.8504
    }
  },
  "mara-bed-frame:v0:wide": {
    "path": "/media/mara-bed-frame-v0-wide.webp",
    "width": 1600,
    "height": 1200,
    "blurDataUrl": "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAADwAQCdASoMAAkAAsBIJYwCdAEUr+HKdIAA/vmY4v4lKWRL/xb+o1Md6td2qNtMgAA=",
    "anchors": {
      "x1": 0.1275,
      "y1": 0.2495,
      "x2": 0.8725,
      "y2": 0.7913
    }
  },
  "mara-bed-frame:v0:square": {
    "path": "/media/mara-bed-frame-v0-square.webp",
    "width": 1200,
    "height": 1200,
    "blurDataUrl": "data:image/webp;base64,UklGRjgAAABXRUJQVlA4ICwAAADQAQCdASoMAAwAAsBIJZQCw7EOjQuMAAD++qcJlCJidb1l9nF6pebJWOgAAA==",
    "anchors": {
      "x1": 0.17,
      "y1": 0.3404,
      "x2": 0.83,
      "y2": 0.7004
    }
  },
  "mara-bed-frame:v1:wide": {
    "path": "/media/mara-bed-frame-v1-wide.webp",
    "width": 1600,
    "height": 1200,
    "blurDataUrl": "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAADQAQCdASoMAAkAAsBIJZQCdAEPhr+ZAAD+92nC5VF1JBPVFKoYri1Iy4VXhyCkOHt1RakQAAA=",
    "anchors": {
      "x1": 0.1275,
      "y1": 0.2495,
      "x2": 0.8725,
      "y2": 0.7913
    }
  },
  "mara-bed-frame:v1:square": {
    "path": "/media/mara-bed-frame-v1-square.webp",
    "width": 1200,
    "height": 1200,
    "blurDataUrl": "data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAADQAQCdASoMAAwAAsBIJZwC7AEOjEztAAD++qbvLZx9yifrBPrreKMceuti/npWY0AAAA==",
    "anchors": {
      "x1": 0.17,
      "y1": 0.3404,
      "x2": 0.83,
      "y2": 0.7004
    }
  },
  "mara-bed-frame-king:wide": {
    "path": "/media/mara-bed-frame-king-wide.webp",
    "width": 1600,
    "height": 1200,
    "blurDataUrl": "data:image/webp;base64,UklGRiQAAABXRUJQVlA4IBgAAAAwAQCdASoMAAkAAsBIJaQAA3AA/vdCAAA=",
    "anchors": {
      "x1": 0.1275,
      "y1": 0.2912,
      "x2": 0.8725,
      "y2": 0.7496
    }
  },
  "mara-bed-frame-king:square": {
    "path": "/media/mara-bed-frame-king-square.webp",
    "width": 1200,
    "height": 1200,
    "blurDataUrl": "data:image/webp;base64,UklGRiQAAABXRUJQVlA4IBgAAAAwAQCdASoMAAwAAsBIJaQAA3AA/vdCAAA=",
    "anchors": {
      "x1": 0.17,
      "y1": 0.3681,
      "x2": 0.83,
      "y2": 0.6727
    }
  },
  "mara-bed-frame-king:pano": {
    "path": "/media/mara-bed-frame-king-pano.webp",
    "width": 1600,
    "height": 900,
    "blurDataUrl": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4WAoAAAAQAAAACwAABgAAQUxQSBUAAAABF3Dx/4iIgkAQwl7PdNSFiP4n8qYAVlA4IBoAAAAwAQCdASoMAAcAAsBIJaQAA3AA/vdGeBAAAA==",
    "anchors": {
      "x1": 0.0978,
      "y1": 0.1904,
      "x2": 0.9022,
      "y2": 0.8504
    }
  },
  "mara-bed-frame-king:v0:wide": {
    "path": "/media/mara-bed-frame-king-v0-wide.webp",
    "width": 1600,
    "height": 1200,
    "blurDataUrl": "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAADwAQCdASoMAAkAAsBIJYwCdAEPAflXbgAA/vmZE9f1KSdVddC9zoNF12qNtMgAAAA=",
    "anchors": {
      "x1": 0.1275,
      "y1": 0.2912,
      "x2": 0.8725,
      "y2": 0.7496
    }
  },
  "mara-bed-frame-king:v0:square": {
    "path": "/media/mara-bed-frame-king-v0-square.webp",
    "width": 1200,
    "height": 1200,
    "blurDataUrl": "data:image/webp;base64,UklGRjgAAABXRUJQVlA4ICwAAADwAQCdASoMAAwAAsBIJZQC7AEO5D0JWAAA/vqnCZQiM0culzsqJd24a4AAAA==",
    "anchors": {
      "x1": 0.17,
      "y1": 0.3681,
      "x2": 0.83,
      "y2": 0.6727
    }
  },
  "mara-bed-frame-king:v1:wide": {
    "path": "/media/mara-bed-frame-king-v1-wide.webp",
    "width": 1600,
    "height": 1200,
    "blurDataUrl": "data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAACwAQCdASoMAAkAAsBIJZQCw7EO/C4wAP74Nz6KYRbzaz3xjIGO0hverlbBWj9M3fAAAA==",
    "anchors": {
      "x1": 0.1275,
      "y1": 0.2912,
      "x2": 0.8725,
      "y2": 0.7496
    }
  },
  "mara-bed-frame-king:v1:square": {
    "path": "/media/mara-bed-frame-king-v1-square.webp",
    "width": 1200,
    "height": 1200,
    "blurDataUrl": "data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAADQAQCdASoMAAwAAsBIJZwC7AEOjEyRAAD++qb+M+JG3jgGuqfUB9cgl7eSx8HFugAAAA==",
    "anchors": {
      "x1": 0.17,
      "y1": 0.3681,
      "x2": 0.83,
      "y2": 0.6727
    }
  }
};
